import 'package:stario/src/models/my_genre_model.dart';

List<Genre> genres = [
  Genre(genre: 'Lo-fi', imagePath: 'assets/genres/lofi.jpg'),
  Genre(genre: 'Hip Hop', imagePath: 'assets/genres/hiphop.jpg'),
  Genre(genre: 'Christian & Gospel', imagePath: 'assets/genres/christian.jpg'),
  Genre(genre: 'Pop', imagePath: 'assets/genres/pop.jpg'),
  Genre(genre: 'R&B', imagePath: 'assets/genres/r&b.jpg'),
  Genre(genre: 'Rap', imagePath: 'assets/genres/rap.jpg'),
  Genre(genre: 'Blues', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Children\'s', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Classical', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Comedy', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Country', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'EDM', imagePath: 'assets/genres/edm.jpg'),
  Genre(genre: 'Folk', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'International', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Jazz', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Latin', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Reggae', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Techno', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Punk', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Metal', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Gaming', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'K-Pop', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Instrumental', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Covers', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Workout', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Romance', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Soul', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Study', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Summer', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Sleep', imagePath: 'assets/genres/blues.jpg'),
];
