import 'package:stario/src/models/genre_model.dart';

List<Genre> genres = [
  Genre(genre: 'Lo-fi', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Hip Hop', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Christian & Gospel', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Pop / Rock', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'R&B', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Rap', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Blues', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Children\'s', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Classical', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Comedy', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Country', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'EDM', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Folk', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'International', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Jazz', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Latin', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Reggae', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Techno', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Punk', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Metal', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Gaming', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'K-Pop', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Instrumental', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Covers', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Workout', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Romance', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Soul', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Study', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Summer', imagePath: 'assets/genres/blues.jpg'),
  Genre(genre: 'Sleep', imagePath: 'assets/genres/blues.jpg'),
];
